-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ########################################################################################
-- AUTOGENERATED HYPR CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- ########################################################################################
--
-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
--
-- autogenerated = 1 # remove this line to remove the warning
-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "DP-2",
	mode = "preferred",
	position = "1920x0",
	scale = 1,
	bitdepth = 10,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "0x360",
	scale = 1,
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch

-- exec-once = waybar & hyprpaper & firefox
-- exec-once=hyprpanel
-- exec-once=swayidle -w

-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- Set programs that you use
local terminal = "alacritty"
local fileManager = "dolphin"
local menu = "rofi -show drun -i"

-- Some default env vars.

hl.env("XCURSOR_SIZE", 24)
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct") -- change to qt6ct if you have that

hl.env("XDG_MENU_PREFIX", "arch-")

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
	input = {
		kb_layout = "us",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
		},
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		numlock_by_default = true,
	},
})

hl.config({
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 5,
		gaps_out = 15,
		border_size = 2,
		layout = "dwindle",
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
	},
})

hl.config({
	cursor = {
		inactive_timeout = 5,
	},
})

--blurls = waybar

hl.config({
	decoration = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		rounding = 10,
		blur = {
			enabled = true,
			size = 5,
			passes = 3,
		},
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
	},
})

hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "rofi" }, blur = true })

hl.config({
	animations = {
		enabled = true,
		-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

hl.config({
	dwindle = {
		-- See https://wiki.h/usr/bin/python3yprland.org/Configuring/Dwindle-Layout/ for more
		preserve_split = true,
		-- you probably want this
	},
})

hl.config({
	master = {
		-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
		-- new_is_master = true
		new_status = "master",
	},
})

-- https://wiki.hypr.land/Configuring/Gestures/#available-gestures
-- gesture = 3, left, workspace, +1
-- gesture = 3, right, workspace, -1

hl.config({
	misc = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		force_default_wallpaper = 0,
		-- Set to 0 to disable the anime mascot wallpapers
	},
})

-- Example per-device config
-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

-- Example windowrule v1
-- windowrule = float, ^(kitty)$
-- Example windowrule v2
-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
--
-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
-- windowrulev2 = forceinput, class:.*

hl.window_rule({
	name = "match_class__",
	match = {
		class = "suppress_event maximize",
	},
	-- TODO: review rule: "match:class.*"
})

-- KDE CONNECT Presentation Mode

hl.window_rule({
	name = "kde-connect",
	match = {
		title = "KDE Connect Daemon",
	},
	opacity = 1,
	border_size = 0,
	no_shadow = true,
	no_anim = true,
	no_focus = true,
	suppress_event = "fullscreen",
	float = true,
	pin = true,
	min_size = { 2560, 1440 },
	move = { 2630, 300 },
})

hl.window_rule({
	name = "match_class_jetbrain",
	match = {
		class = "no_follow_mouse true",
	},
	-- TODO: review rule: "match:class jetbrains-studio"
})

-- windowrulev2=opacity 1, title:KDE Connect Daemon
-- windowrulev2=noblur, title:KDE Connect Daemon
-- windowrulev2=noborder, title:KDE Connect Daemon
-- windowrulev2=noshadow, title:KDE Connect Daemon
-- windowrulev2=noanim, title:KDE Connect Daemon
-- windowrulev2=nofocus, title:KDE Connect Daemon
-- windowrulev2=suppressevent fullscreen, title:KDE Connect Daemon
-- windowrulev2=float, title:KDE Connect Daemon
-- windowrulev2=pin, title:KDE Connect Daemon
-- windowrulev2=minsize 1920 1080, title:KDE Connect Daemon
-- windowrulev2=move 2630 300, title:KDE Connect Daemon
-- windowrulev2=nofollowmouse, class:jetbrains-studio

hl.window_rule({
	name = "match_class___com__n",
	match = {
		class = "float true",
	},
	-- TODO: review rule: "match:class ^(com\\.nextcloud\\.desktopclient\\.nextcloud)$"
})

hl.window_rule({
	name = "match_class___com__n",
	match = {
		class = "no_initial_focus true",
	},
	-- TODO: review rule: "match:class ^(com\\.nextcloud\\.desktopclient\\.nextcloud)$"
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind("CTRL + ALT" .. " + " .. "T", hl.dsp.exec_cmd("alacritty"))
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())
hl.bind("CTRL + ALT" .. " + " .. "M", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("rofi -show run"))
hl.bind("ALT" .. " + " .. "space", hl.dsp.exec_cmd("rofi -show drun -i"))
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "tab", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| rofi -dmenu| cliphist decode| wl-copy"))
hl.bind("CTRL + ALT" .. " + " .. "Delete", hl.dsp.exec_cmd("~/.config/scripts/power.sh"))
hl.bind(mainMod .. " + " .. "period", hl.dsp.exec_cmd("~/.config/scripts/dmoji.sh"))
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

-- Move window

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.window.move({ direction = "d" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "h", hl.dsp.focus({ workspace = -1 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "l", hl.dsp.focus({ workspace = "+1" }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))
hl.bind(mainMod .. " + " .. "SHIFT + CTRL" .. " + " .. "h", hl.dsp.window.move({ workspace = "-1" }))
hl.bind(mainMod .. " + " .. "SHIFT + CTRL" .. " + " .. "l", hl.dsp.window.move({ workspace = "+1" }))

-- Grouping
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "G", hl.dsp.group.toggle())
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "N", hl.dsp.group.next())
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "P", hl.dsp.group.next({ forward = false }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
-- bind = $mainMod SHIFT, S, movetoworkspace, special:magic

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e+1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Example volume button that will activate even while an input inhibitor is active
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +10%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"))
hl.bind(
	mainMod .. " + " .. "ALT" .. " + " .. "MINUS",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"),
	{ locked = true }
)
hl.bind(
	mainMod .. " + " .. "ALT" .. " + " .. "EQUAL",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+"),
	{ locked = true }
)
hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "P", hl.dsp.exec_cmd("playerctl -p spotify play-pause"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl -p spotify play-pause"))

-- Screen brightness

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +5%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd('grim -g "$(slurp)"-| wl-copy'))
hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "S", hl.dsp.exec_cmd("grim-| wl-copy"))
hl.bind(
	mainMod .. " + " .. "CTRL" .. " + " .. "S",
	hl.dsp.exec_cmd(
		"grim ~/Pictures/Screenshots/$(date +'screenshot_%Y-%m-%d-%H%M%S.png') && notify-send -u low Grim \"Screenshot saved\""
	)
)
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("hyprpicker| wl-copy"))

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("waybar > ~/.local/state/waybar.log")
	hl.exec_cmd("dunst")
	hl.exec_cmd("/usr/lib/kdeconnectd")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("awww img ~/Pictures/Wallpapers/quirrel.gif --transition-type center")
	hl.exec_cmd("~/.config/scripts/battery_poll.sh")
	hl.exec_cmd("kdeconnectd")
	hl.exec_cmd("kdeconnect-indicator")
	hl.exec_cmd("steam -silent")
	hl.exec_cmd("otd-daemon")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("nextcloud")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
